### PR TITLE
Fixes Host view permissions to search by puppetclass

### PR DESCRIPTION
**Pull request by Manisha15**

### CODE REVIEW

**Comment by Manisha15** [comment]
Fixes issue #315

**Review by nadjaheitmann — COMMENTED** [review]
I am not exactly sure what the code is supposed to do, but at the first glance it looks like the code prevents users to access hosts that they are not authorized to access. If so, I suppose that this restriction should not be removed.

**Comment by Manisha15** [comment]
> I am not exactly sure what the code is supposed to do, but at the first glance it looks like the code prevents users to access hosts that they are not authorized to access. If so, I suppose that this restriction should not be removed.

I have reverted the authorization permissions and now this should work. We should also add the documentation somewhere that `search by puppetclass` is only available for users with `view_hosts` role.

**Comment by Ron-Lavi** [comment]
@laugmanuel can I ask you to verify the fix again?

**Comment by laugmanuel** [comment]
@Ron-Lavi still works!

**Comment by nadjaheitmann** [comment]
Merged, thanks @Manisha15 !

**Comment by nadjaheitmann** [comment]
CP to 4.1: ab289f86b14ea266e5c74750fddc4d7866a4b0f7

**Pull request merged**
