### PR TITLE
Fixes #386 - Change search parameter to puppetclass

### LINKED ISSUE #386: Puppet Classes page has incorrect link to host search page to view hosts with class
When you're on the Puppet Classes page: www.example.com/foreman_puppet/puppetclasses the hosts column shows the number of hosts with a class. Clicking the link in Foreman 3.9.1 takes you to the hosts page, displays all hosts, and displays an error message "Field 'class' not recognized for searching!"

Those links look like this:

https://www.example.com/hosts?search=class+%3D+CLASSNAMEHERE

But I think they should be puppetclass not class

https://www.example.com/hosts?search=puppetclass+%3D+CLASSNAMEHERE

### PR DESCRIPTION
**Pull request by nadjaheitmann**

### CODE REVIEW

**Comment by nadjaheitmann** [comment]
We missed that in https://github.com/theforeman/foreman_puppet/commit/b3a18fb2e58589221999424f046cf95462bc5687

**Comment by stejskalleos** [comment]
@ekohl any idea why the CI has not been triggered?

**Comment by ekohl** [comment]
I see CI checks. Perhaps they were slow? GH issue?

**Comment by nadjaheitmann** [comment]
They came back once I rebased the branch with #383

**Pull request merged**
