### PR TITLE
Add Puppet Environment column to Hosts page

### LINKED ISSUE #210: `Puppet Environment` column missing on Hosts page
Details see here: https://community.theforeman.org/t/foreman-3-0-environment-column-nao-available-on-hosts-page/25720/4

### PR DESCRIPTION
**Pull request by nadjaheitmann**
Fixes #210

### CODE REVIEW

**Comment by ezr-ondrej** [comment]
I really don't like using Deface just for this :(
But if you feel like we should, I'll not block this...

**Comment by nadjaheitmann** [comment]
Any other way to patch this?

**Comment by nadjaheitmann** [comment]
I get your point - would be nice if folks could provide more insight on why they want it back :)

**Comment by nadjaheitmann** [comment]
@ezr-ondrej There we go with pagelets :) 
Needs https://github.com/theforeman/foreman/pull/9126 from core

**Comment by nadjaheitmann** [comment]
CP 2.0: 9352e708dbf6503159387db3bfff467e9a48b6ac

**Pull request merged**
