### PR TITLE
Fixes #35949 - move select_multiple_puppet_proxy to the plugin

### PR DESCRIPTION
**Pull request by Ron-Lavi**
Corresponding PR in https://github.com/theforeman/foreman/pull/9636

### CODE REVIEW

**Review by nadjaheitmann — APPROVED** [review]
I patched a test system and it seems to fix the isse.

**Comment by Ron-Lavi** [comment]
> I patched a test system and it seems to fix the issue.

Hey @nadjaheitmann, even without the corresponding Foreman PR?

**Comment by nadjaheitmann** [comment]
> > I patched a test system and it seems to fix the issue.
> 
> Hey @nadjaheitmann, even without the corresponding Foreman PR?

I tested with the corresponding Foreman PR, I did not without.

**Comment by nadjaheitmann** [comment]
> I tested with the corresponding Foreman PR, I did not without.

Does not work without the change in Foreman ;)

**Comment by nadjaheitmann** [comment]
> > @laugmanuel Could you also verify, please?
> 
> Unfortunately, I don't have a somewhat "new" and working Foreman instance I could use for testing - sorry :(

Okay. But the issue should also affect Foreman 3.1, shouldn't it? In case you need the fix.

**Comment by nadjaheitmann** [comment]
Shall we go ahead and merge it? Even if the patch is not applied on Foreman, the change does not break anything.

**Comment by laugmanuel** [comment]
> Okay. But the issue should also affect Foreman 3.1, shouldn't it? In case you need the fix.

Oh you are completely right! Thank's for the heads-up. It's very uncommon for us to use that feature and therefore we did not even notice.  
I've applied both patches and everything looks fine afterwards!

**Review by laugmanuel — APPROVED** [review]

**Pull request merged**
