### PR TITLE
Add Packit

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Comment by nadjaheitmann** [comment]
@stejskalleos Thanks for notification. I am fine if @evgeni approves as I am not really familiar with this topic.

**Comment by stejskalleos** [comment]
You can easily test it:
On EL 8:
```
yum install -y dnf-plugins-core
dnf copr enable packit/theforeman-foreman_puppet-361 centos-stream-8-x86_64 -y
dnf install -y rubygem-foreman_puppet-6.0.0-2.20230622195317344803.pr361.2.g08fac19.el8.noarch

Updating Subscription Management repositories.
Copr repo for theforeman-foreman_puppet-361 owned by packit                                                        12 kB/s | 6.8 kB     00:00    
Error: 
 Problem: conflicting requests
  - nothing provides foreman >= 3.7 needed by rubygem-foreman_puppet-6.0.0-2.20230622195317344803.pr361.2.g08fac19.el8.noarch
```

the error is expected if you try it on machine without foreman, but at least you can see that the rpm package is available for testing.

More info here https://community.theforeman.org/t/packit-for-foreman-get-production-rpms-from-prs/32412

**Comment by nadjaheitmann** [comment]
I assume I cannot add packit to our scc manager repo, for example? :D

**Comment by evgeni** [comment]
> I assume I cannot add packit to our scc manager repo, for example? :D

you absolutely can!

ping me monday on IRC and I'll talk you through the process :)

**Pull request merged**
