### PR TITLE
Fix config group links

### PR DESCRIPTION
**Pull request by nadjaheitmann**

### CODE REVIEW

**Review by ezr-ondrej — APPROVED** [review]
Thanks @nadjaheitmann.
Care to add some specs to verify this? I know it's not very straight forward, so I dont insist :)

**Comment by nadjaheitmann** [comment]
@ezr-ondrej If you point me to an example how to verify links using specs, I can give it a try :)

**Comment by ezr-ondrej** [comment]
You can take a look at `spec/views/foreman_puppet_enc/environments/index.html.erb_spec.rb`, and use `have_selector` to verify the link. but the specs have quite artificial test environments, so it's not 100% testing that the links will work in prod if they work in the spec.

**Comment by ezr-ondrej** [comment]
Thanks @nadjaheitmann

**Pull request merged**
