### PR TITLE
GraphQL fixes

### PR DESCRIPTION
**Pull request by kamils-iRonin**

### CODE REVIEW

**Review by timogoebel — APPROVED** [review]

**Comment by timogoebel** [comment]
Thanks!

**Comment by ezr-ondrej** [comment]
Do we want to cherry-pick this? I do not agree with `2.6` version btw, it is nonexistent version :)

**Comment by kamils-iRonin** [comment]
> Do we want to cherry-pick this?

Yes, I think it should be cherry-picked. 

> I do not agree with `2.6` version btw, it is nonexistent version :)

Changed to `2.6` to make tests on `develop` pass (`SETTINGS[:version].notag` returned `2.6.0`). I think we can set `3.0` back now.

**Comment by ezr-ondrej** [comment]
> Changed to `2.6` to make tests on `develop` pass (`SETTINGS[:version].notag` returned `2.6.0`). I think we can set `3.0` back now.

Yeah, I get it, good thing it's in separate commit :)

**Comment by ezr-ondrej** [comment]
CP 1.0: 48d6ee7

**Pull request merged**
