### PR TITLE
Fix translations

### PR DESCRIPTION
**Pull request by stejskalleos**
Various fixes and improvements

fixes bf2ec86

### CODE REVIEW

**Comment by stejskalleos** [comment]
@nadjaheitmann This should be the last & correct translation fix, later there will be another PR with translated strings.

**Review by nadjaheitmann — APPROVED** [review]

**Comment by nadjaheitmann** [comment]
Thanks @stejskalleos 
Why is there this commit d3cd19eee65c0b004d6b35e80cec043055b36ecc if there will be another translations commit later?

**Comment by stejskalleos** [comment]
> Why is there this commit https://github.com/theforeman/foreman_puppet/commit/d3cd19eee65c0b004d6b35e80cec043055b36ecc if there will be another translations PR later?

The other PR will be with the updated translations for each language, from the translation team. When the translations will be ready, we pull them to the repo and ship them with a released gem.

**Comment by stejskalleos** [comment]
@nadjaheitmann are you ok with the changes & the comment, can we merge?

**Review by nadjaheitmann — APPROVED** [review]

**Pull request merged**
