### PR TITLE
Re-route API core routes to plugin controllers

### LINKED ISSUE #152: Redirect core routes to use plugin routes
Refers to https://github.com/theforeman/foreman_puppet/pull/151#issuecomment-851874564 .

As of now, old API routes are still active. 
```
[I|app|e93963d1] Started GET "/api/puppetclasses" for 192.168.121.1 at 2021-06-01 06:45:45 +0000$
[I|app|e93963d1] Processing by Api::V2::PuppetclassesController#index as JSON
```
Two possibilities:
1) redirect the routes for now (seems easier in terms of implementation and more user friendly for current API users) 
2) disable routes (we be done eventually, even if we implement the redirection for now)

### PR DESCRIPTION
**Pull request by nadjaheitmann**
Fixes #152

### CODE REVIEW

**Comment by nadjaheitmann** [comment]
Seems there is something wrong with rubocop?

**Comment by sbernhard** [comment]
> Seems there is something wrong with rubocop?

I guess, another PR is need to fix the rubocop complains.

**Comment by nadjaheitmann** [comment]
> I guess, another PR is need to fix the rubocop complains.
Yeah, I will look into this.

**Comment by nadjaheitmann** [comment]
Right now, I have simply re-directed the controllers, which seems to work. I have seen that (re)routing is often restricted for specific actions. What is the best practice for this case?

**Comment by ezr-ondrej** [comment]
We have this in core in the extraction PR, where we reroute if the plugin is installed. Though this might be a better way to go as in core we are checking wheter a plugin is installed in routes file, depends how long we want to keep the rerouting. Do we wanna get rid of it in two versions? then lets keep it in core, if we wanna do this permanently, lets merge this.

**Comment by timogoebel** [comment]
> if we wanna do this permanently, lets merge this.

I vote for having it as part of the plugin. This keeps all puppet related code here and we don't have to do core changes in the future.

**Comment by nadjaheitmann** [comment]
> Do we wanna get rid of it in two versions? then lets keep it in core, if we wanna do this permanently, lets merge this.

We might be a more flexible how we want to handle the routing if we merge it here and Foreman core routes are cleaner. Then we can avoid something like this:
https://github.com/theforeman/foreman/blob/develop/config/routes/api/v2.rb#L207

**Comment by nadjaheitmann** [comment]
If we were to merge this, is there anything else that needs to be done for the PR?

**Comment by timogoebel** [comment]
I haven't done a thorough review, but basically, this looks good.
I believe we need to check if permission wise anything needs to be done.
In foreman_dlm for example we have this check as part of the CI. I suggest we also add it here. The check makes sure that for all routes correct access permissions are defined.

Test that we should add to the CI:

https://github.com/dm-drogeriemarkt/foreman_dlm/blob/f230261ce5be8d98d199333a5015854a87b7995d/.github/workflows/ci.yml#L69

API to define permissions for routes (as an example):
https://github.com/dm-drogeriemarkt/foreman_dlm/blob/f230261ce5be8d98d199333a5015854a87b7995d/lib/foreman_dlm/engine.rb#L32-L35

**Comment by timogoebel** [comment]
Looks good. Can we drop the WIP-Label?

**Comment by timogoebel** [comment]
Thanks!

**Pull request merged**
