### PR TITLE
Bump foreman_puppet to 5.1.3

### PR DESCRIPTION
**Pull request by stejskalleos**

### CODE REVIEW

**Review by nadjaheitmann — APPROVED** [review]

**Comment by nadjaheitmann** [comment]
LGTM. Thanks @stejskalleos

**Comment by nadjaheitmann** [comment]
Will this be picked up by the packaging bot or do we have to package it manually?

**Comment by stejskalleos** [comment]
I guess I have to do it manually, which Foreman is using puppet 5.x version?

**Comment by nadjaheitmann** [comment]
3.5 and 3.6

**Comment by stejskalleos** [comment]
3.6 PR: https://github.com/theforeman/foreman-packaging/pull/9812

**Pull request merged**
