### PR TITLE
Ensure that Global ID contains modulized model name

### PR DESCRIPTION
**Pull request by kamils-iRonin**
needs https://github.com/theforeman/foreman/pull/9458

### CODE REVIEW

**Comment by Ron-Lavi** [comment]
Can you rebase now after https://github.com/theforeman/foreman_puppet/pull/322 got merged?

**Comment by Ron-Lavi** [comment]
@kamils-iRonin LGTM, is it good to merge?

**Comment by kamils-iRonin** [comment]
@Ron-Lavi yes, fell free to merge 🙂

**Comment by Ron-Lavi** [comment]
Thanks @kamils-iRonin !

**Pull request merged**
